
nodes:
  Node_I1:
    type: input
  Node_I2:
    type: input
  Node_amp:
    type: block
    equation: 5*s
  Node_sum:
    type: sum
  Node_O1:
    type: output
  Node_split:
    type: split
  Node_O2:
    type: output

connections:
  - Node_I1 - Node_sum/0/+
  - Node_I2 - Node_amp
  - Node_amp - Node_sum/1/-
  - Node_sum - Node_split
  - Node_split/0 - Node_O1
  - Node_split/1 - Node_O2
