
nodes:
  I1:
    type: input
  I2:
    type: input
  Node_split_amp:
    type: split
  Node_amp_1:
    type: block
    equation: 5*s
  Node_amp_2:
    type: block
    equation: s**2
  Node_amp_p:
    type: proportional
    k: 5
  Node_join_amp:
    type: sum
  Node_sum:
    type: sum
  O1:
    type: output
  Node_split:
    type: split
  O2:
    type: output

connections:
  - I1 - Node_sum/+
  - I2 - Node_split_amp
  - Node_split_amp - Node_amp_p
  - Node_amp_p - Node_join_amp/-
  - Node_split_amp - Node_amp_1
  - Node_amp_1 - Node_amp_2
  - Node_amp_2 - Node_join_amp/+
  - Node_join_amp - Node_sum/-
  - Node_sum - Node_split
  - Node_split - O1
  - Node_split - O2
